### ISSUE TITLE
 Peer-to-peer code review

### ISSUE THREAD

**Issue by kerlos-bahaa** [Mofuhidy/to-Do-list#8]

**Comment by kerlos-bahaa** [comment]
great project with a clean code i really like the javascript is simple and direct

**Comment by khanh-devos** [comment]
Great design always: 

- [x] kindly use regular function inside a class as a property because the class prototype will not receive that arrow function,  [https://www.charpeni.com/blog/arrow-functions-in-class-properties-might-not-be-as-great-as-we-think](url)

**Comment by aradradev** [comment]
👍 Good job, you implemented all the requirements for this project so far.

However, there is some issue with the icon adding a new Task, it should be implemented when the user would like to clique in the icon. Additionally in your Readme file, you should add a valid link to your live demo.

Overall there is nothing else to say other than you did an amazing job with a good design.

**Comment by Mofuhidy** [comment]
Thank you, guys, for your kind feedback. I'll work on the issues
